- name: variables in ansible
  hosts: mongodb
  # This is play level variables
  vars:
    COURSE: DevOPS
    TRAINER: Sivakumar
    DURATION: 110HRS
  tasks: 
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello iam learning Ansible"
  - name: print Variables
    ansible.builtin.debug:
      msg: "Hello, Iam learning {{COURSE}}, Trainer is{{TRAINER}}, Duration is {{DURATION}}"
